name: build-test-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install modules
      run: npm install
    # - name: Initiate app
    #   run: npm run start
    - name: Start unit tests
      run: npm test:unit
    - name: Display my students username
      run: echo 'mdzhut200'

